assignment1/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import PostListVies, PostDetailView, PostUpdateView, PostDeleteView, PostCreateView, CommentUpdateView, \
    CommentDeleteView, CommentCreateVew

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', PostListVies.as_view(), name='post-list'),
    path('posts/following/', PostListVies.as_view(), name='post-following'),  # Add this
    path('posts/followers/', PostListVies.as_view(), name='post-followers'),
    path('post-edit/<int:pk>/', PostUpdateView.as_view(), name='post-edit'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post-delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('create-post/', PostCreateView.as_view(), name='create-post'),
    path('comment/<int:pk>/edit', CommentUpdateView.as_view(), name='comment-edit'),
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name='comment-delete'),
    path('post/<int:pk>/comment', CommentCreateVew.as_view(), name='comment-create'),
]

assignment1/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignment1/blog/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Author(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False, related_name='authors')

    def __str__(self):
        return f'{self.pk} - {self.name}'

class Post(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField(max_length=2000, null=False, blank=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created at")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")
    image = models.ImageField(upload_to='post-images', null=True, blank=True)

    def __str__(self):
        return f'{self.pk} - {self.title} /n {self.author}'

class Comment(models.Model):
    body = models.TextField(max_length=2000, null=False, blank=False, verbose_name="Comment")
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False, related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=False, blank=False, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created at")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")

    def __str__(self):
        return f'{self.pk} - {self.body[:20]} /n {self.author} post: {self.post}    '

assignment1/templates/main-page/post/create_post.html
{% extends 'main-page/base.html' %}
{% block content %}
<div class="container mt-5 form-control">
    <label class="form-control text-center justify-content-center">Creating New Post...</label>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="text-center">
              <button type="submit" class="btn btn-outline-success mt-3 mb-3">Create the post</button>
        </div>
    </form>
</div>
{% endblock %}

assignment1/templates/main-page/post/delete_post.html
{% extends 'main-page/base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="card mb-4" style="max-width: 600px; margin: auto;">
        <div class="card-body text-center">
            <h5 class="card-title text-danger">Are you sure you want to delete the following post?</h5>
            {% if post.image %}
                    <img src="{{ post.image.url }}" class="card-img-top" alt="problems with the image of post-{{ post.pk }}">
                        {% else %}
            {% endif %}
            <h6 class="mb-3">{{ post.title }}</h6>
            <p class="text-muted">Author: {{ post.author }}</p>
            <p>{{ post.body }}</p>
            <p class="text-danger"><strong>This action cannot be undone.</strong></p>
            <form action="{% url 'post-delete' post.pk %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger">Delete Post</button>
                <a href="{% url 'post-list' %}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

assignment1/templates/main-page/post/post-detail.html
{% extends 'main-page/base.html' %}
{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">{{ post.title }}</h2>
    <div class="card mb-4" style="max-width: 600px; margin: auto;">
        {% if post.image %}
                    <img src="{{ post.image.url }}" class="card-img-top" alt="problems with the image of post-{{ post.pk }}">
                        {% else %}
                    {% endif %}
        <div class="card-body">
            <h5 class="card-title">Author: {{ post.author }}</h5>
            <p class="card-text">{{ post.body }}</p>
            <p class="text-muted">Posted on: {{ post.created_at }}</p>
            <a href="{% url 'post-list' %}" class="btn btn-secondary">Back to Posts</a>
            {% if request.user == post.author %}
            <a href="{% url 'post-edit' post.pk %}" class="btn btn-primary">Edit Post</a>
            {% endif %}
        </div>
    <div style="margin: 10px 20px">
        <div class="mt-3">
                    <h6>Comments:</h6>
                    {% for comment in comments %}
                        <div class="form-control comment mb-2">
                            <strong>{{ comment.author }}:</strong> {{ comment.body }}
                            {% if request.user == comment.author %}
                                <a href="{% url 'comment-edit' comment.pk %}" class="btn btn-outline-secondary mt-2 mb-2">Edit</a>
                                <a href="{% url 'comment-delete' comment.pk %}" class="btn btn-outline-danger">Delete</a>
                            {% endif %}
                        </div>
                    {% empty %}
                        <p>No comments yet.</p>
                        {% if not request.user.is_authenticated %}
                            <a href="{% url 'login' %}"  class="text-danger">You should to login to add comments</a>
                            {% else %}
                            <a href="{% url 'comment-create' post.pk %}" class="text-secondary">Add comment</a>
                        {% endif %}
                    {% endfor %}
        </div>
    </div>
    </div>
</div>
{% endblock %}

assignment1/templates/main-page/post/posts.html
{% extends 'main-page/base.html' %}
{% block content %}
<div id="posts" class="container mt-5 w-50">
    <div class="form-control">


{#        <a href="{% url 'post-following' %}" class="text-center mt-2 mb-2 form-control btn btn-outline-secondary">Following</a>#}
{#        <a href="{% url 'post-followers' %}" class="text-center mt-2 mb-2 form-control btn btn-outline-success">Followers</a>#}
        <a href="{% url 'post-list' %}" class="text-center mt-2 mb-2 form-control btn btn-outline-success">Recent Posts</a>
        <form class="form-inline" style="height: 45px" method="get">
            {% csrf_token %}
                <ul>
                    <li class="list-group-item list-group-item-action d-flex justify-content-between main-search mt-5" style="margin-top: 3px">
                        <input type="search" name="search" class="form-control" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-secondary" id="button-addon2" style="margin-left: 10px">Search</button>
                    </li>
                </ul>
        </form>
    </div>

    <div class="text-center mb-4">
        {% if request.user.is_authenticated %}
            <a href="{% url 'create-post' %}" class="btn btn-success mt-3">Create New Post</a>
            {% else %}
            <a href="{% url 'login' %}"  class="text-danger">You should to login to create comment</a>
        {% endif %}

    </div>
    <div class="row">
        {% for post in posts %}
            <div class="col-12 mb-4">
                <div class="card">
                    {% if post.image %}
                        <img src="{{ post.image.url }}" class="card-img-top" alt="Image of post-{{ post.pk }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ post.pk }}. {{ post.title }}</h5>
                        <a href="{% url 'profile' post.author.pk %}" class="card-text"><strong>{{ post.author }}:</strong> {{ post.body|truncatewords:50 }}</a>
                        <p class="text-muted">Last updated at: {{ post.created_at }}</p>
                        <a href="{% url 'post-detail' post.pk %}" class="btn btn-primary">Read More</a>
                        {% if post.author == request.user %}
                            <a href="{% url 'post-delete' post.pk %}" class="btn btn-danger">Delete</a>
                        {% endif %}
                    </div>
                <div  style="margin: 10px 20px">
                    <div class="form-control">
                    <h6>Comments:</h6>
                    {% if post.comments.all %}
                        {% for comment in post.comments.all %}
                            <div class="comment mb-2">
                                <strong>{{ comment.author }}:</strong> {{ comment.body }}
                            </div>
                        {% endfor %}
                    {% else %}
                        <p>No comments yet.</p>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'comment-create' post.pk %}" class="text-secondary">Add comment</a>
                        {% else %}
                        <a href="{% url 'login' %}"  class="text-danger">You should to login to add comments</a>
                    {% endif %}
                        </div>
                    </div>
                </div>


            </div>
        {% endfor %}
    </div>
    {% include 'main-page/pagination.html' %}
</div>
{% endblock %}

assignment1/templates/main-page/post/update-post.html
{% extends 'main-page/base.html' %}

{% block content %}
    <div class="card mt-3 container w-50 mb-3">
    <h1 class="text-center mt-5 mb-3">Post Edit</h1>
     <form action="{% url 'post-edit' post.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% for error in non_field_errors %}
            <p class="form-error">{{ error }}</p>
        {% endfor %}

     <div class="mb-3">
         <label for="id_title" class="form-label">Title</label>
         <input type="text" name="title" id="id_title" class="form-control" value="{{ post.title }}">
     </div>

     <div class="mb-3">
         <label for="id_body" class="form-label">Content</label>
         <input type="text" name="body" id="id_body" class="form-control" value="{{ post.body }}">
     </div>

     <div class="mb-3">
         <label for="productImage" class="form-label">Product Image</label>
         {% if product.image %}
             <img src="{{ post.image.url }}" alt="problems with the image of post-{{ post.pk }}" style="max-width: 200px; margin-top: 10px;">
               <div class="mt-3">
                 {{ form.image }}
               </div>
         {% else %}
            {{ form.image }}
         {% endif %}
     </div>

     <button type="submit" class="btn btn-outline-success mt-3 mb-3">Update</button>
     <button class="btn btn-outline-secondary mt-3 mb-3">Cancel</button>

     </form>
    </div>
{% endblock %}