assignment1/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import PostListVies, PostDetailView, PostUpdateView, PostDeleteView, PostCreateView, CommentUpdateView, \
    CommentDeleteView, CommentCreateVew

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', PostListVies.as_view(), name='post-list'),
    path('posts/following/', PostListVies.as_view(), name='post-following'),  # Add this
    path('posts/followers/', PostListVies.as_view(), name='post-followers'),
    path('post-edit/<int:pk>/', PostUpdateView.as_view(), name='post-edit'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post-delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('create-post/', PostCreateView.as_view(), name='create-post'),
    path('comment/<int:pk>/edit', CommentUpdateView.as_view(), name='comment-edit'),
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name='comment-delete'),
    path('post/<int:pk>/comment', CommentCreateVew.as_view(), name='comment-create'),
]

assignment1/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignment1/user/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import UserDetailView, UserUpdateView, PasswordChangeView

urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_view, name='register'),
    path('profile/<int:pk>', UserDetailView.as_view(), name='profile'),
    path('profile/edit', UserUpdateView.as_view(), name='edit'),
    path('change-password', PasswordChangeView.as_view(), name='change-password'),
    path('follow/<str:username>', views.follow_user, name='follow'),
    path('unfollow/<str:username>', views.unfollow_user, name='unfollow'),
]

assignment1/user/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, related_name='profile', verbose_name="profile")
    number = models.CharField(max_length=50, verbose_name="number", null=True, blank=True)
    birth_date = models.DateField(verbose_name='birth date', null=True, blank=True)
    avatar = models.ImageField(upload_to='user_pics', verbose_name='avatar', null=True, blank=True)
    followers = models.ManyToManyField(get_user_model(), related_name='followers', verbose_name='followers', blank=True, symmetrical=False)

    def __str__(self):
        return self.user.get_full_name()

class Follow(models.Model):
    follower = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='follower', verbose_name="follower")
    following = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='following', verbose_name="following")

    def __str__(self):
        return f'{self.follower}'

assignment1/user/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

from .models import Profile

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput(), required=True, strip=False)
    password_confirm = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(), required=True, strip=False)

    def clean(self):
        cleaned_data = super().clean()
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if password != password_confirm:
            raise forms.ValidationError('Passwords must match')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'password_confirm', 'first_name', 'last_name', 'email')


class UserEditForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'First Name', 'last_name': 'Last Name', 'email': 'Email'}

        widgets = {'username': forms.TextInput(attrs={'class': 'form-control w-50'}),
                   'first_name': forms.TextInput(attrs={'class': 'form-control w-50'}),
                   'last_name': forms.TextInput(attrs={'class': 'form-control w-50'}),
                   'email': forms.EmailInput(attrs={'class': 'form-control w-50'}),}

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('number', 'birth_date', 'avatar')
        labels = {'number': 'Number', 'birth_date': 'Birth Date', 'avatar': 'Avatar'}

        widgets = {'number': forms.TextInput(attrs={'class': 'form-control w-50'}),
                   'birth_date': forms.DateInput(attrs={'class': 'form-control w-50', 'type':'date'}),
                   'avatar': forms.FileInput(attrs={'class': 'form-control w-50'})}

class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Password', strip=False)
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Password Confirm', strip=False)
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Old password', strip=False)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Password don't match")

        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get("old_password")

        if not self.instance.check_password(old_password):
            raise forms.ValidationError("Old password is incorrect")

        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ('old_password', 'password', 'password_confirm')

assignment1/user/views.py
from lib2to3.fixes.fix_input import context

from django.contrib.auth import authenticate, login, logout, get_user, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import DetailView, UpdateView

from .forms import RegistrationForm, ProfileEditForm, PasswordChangeForm, UserEditForm
from .models import Profile, Follow



# Create your views here.

@login_required
def follow_user(request, username):
    follow_user = get_object_or_404(User, username=username)

    if request.user != follow_user:
        Follow.objects.get_or_create(follower=request.user, following=follow_user)

    return redirect('profile', follow_user.pk)

@login_required
def unfollow_user(request, username):
    user_to_unfollow = get_object_or_404(User, username=username)
    if request.user != user_to_unfollow:
        Follow.objects.get(follower=request.user, following=user_to_unfollow).delete()

    return redirect('profile', user_to_unfollow.pk)

def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            next = request.GET.get('next')
            if next:
                return redirect(next)
            return redirect('index')
        else:
            context['error'] = True
    return render(request, 'main-page/user/login.html')

@login_required
def logout_view(request):
    logout(request)
    next = request.GET.get('next')
    if next:
        return redirect(next)
    return redirect('index')

def register_view(request):
    if request.user.is_authenticated:
        return redirect('index')
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect('index')
    else:
        form = RegistrationForm()
    return render(request, 'main-page/user/register.html', context={'form': form})

class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'main-page/user/profile.html'
    context_object_name = 'user_object'

    # is_following = Follow.objects.filter(follower=request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        user = self.get_object()
        context['followers'] = Follow.objects.filter(following=user)
        context['following'] = Follow.objects.filter(follower=user)
        context['current_user'] = user
        print(context['followers'])
        print('-------------------')
        print(context['following'])
        context['is_following'] = Follow.objects.filter(follower=self.request.user, following=user).exists()

        return context

    def get_queryset(self):
        return get_user_model().objects.all()

    def get_object(self):
        return get_user_model().objects.get(pk=self.kwargs['pk'])


class UserUpdateView(LoginRequiredMixin,UpdateView):
    model = get_user_model()
    form_class = UserEditForm
    template_name = 'main-page/user/profile-edit.html'
    context_object_name = 'user_object'

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
            print(kwargs)
        return super().get_context_data(**kwargs)

    def get_profile_form(self):
        profile_form = {'instance': self.object.profile}
        if self.request.method == 'POST':
            profile_form['data'] = self.request.POST
            profile_form['files'] = self.request.FILES
            # print(profile_form)
        return ProfileEditForm(**profile_form)

    def get_success_url(self):
        return reverse('profile')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)


    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return render(context)

    def get_object(self, queryset=None):
        return self.request.user

class PasswordChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = PasswordChangeForm
    template_name = 'main-page/user/change-password.html'
    context_object_name = 'user_object'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse('login')

assignment1/templates/main-page/user/change-password.html
{% extends 'main-page/base.html' %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title">Change Password</h1>
                 <form action="{% url 'change-password' %}" method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                    {% for field in form %}
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <span class="input-group-text">{{ field.label }}</span>
                                        {{ field }}
                                    </div>
                                </div>
                            {% for errors in field.errors %}
                                <p class="text-danger">{{ errors }}</p>
                            {% endfor %}

                    {% endfor %}
                 <button type="submit" class="btn btn-outline-secondary">Submit</button>
                 </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

assignment1/templates/main-page/user/login.html
{% extends 'main-page/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <h1 class="text-center">Login</h1>
                <form action="{% url 'login' %}?next={{ request.GET.next }}" method="post" class="form-control">
                    {% csrf_token %}
                    {% if has_error %}
                        <p style="color: red">Invalid username or password!</p>
                    {% endif %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Username</label>
                        <input type="text" name="username" id="username" class="form-control">
                    </div>

                    <div class="mb-3">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" name="password" id="password" class="form-control">
                    </div>

                    <button type="submit" class="btn btn-outline-success btn-block mt-3">Login</button>
                    <a href="{% url 'register' %}" class="btn btn-outline-primary btn-block mt-3">Register</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

assignment1/templates/main-page/user/profile-edit.html
{% extends 'main-page/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form action="{% url 'edit' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <span class="input-group-text">{{ field.label }}</span>
                                        {{ field }}
                                    </div>
                                </div>
                            {% for errors in field.errors %}
                                <p class="text-danger">{{ errors }}</p>
                            {% endfor %}

                        {% endfor %}
                        {% for field in profile_form %}
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <span class="input-group-text">{{ field.label }}</span>
                                        {{ field }}
                                    </div>
                                </div>
                            {% for errors in field.errors %}
                                <p class="text-danger">{{ errors }}</p>
                            {% endfor %}

                        {% endfor %}
                        <button type="submit" class="btn btn-outline-success mt-3">Submit</button>
                        <a href="{% url 'post-list' %}" class="btn btn-outline-secondary mt-3">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

assignment1/templates/main-page/user/profile.html
{% extends 'main-page/base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h1 class="card-title">{{ user_object.username }}'s Profile</h1>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                {% if user_object.profile.avatar %}
                                    <img src="{{ user_object.profile.avatar.url }}" class="img-fluid" style="width: 200px" alt="avatar">
                                        {% else %}
                                        <div style="">
                                            <img src="{% static 'images/user.png' %}" style="width: 200px" alt="default">
                                         </div>
                                {% endif %}
                            </div>
                            <div class="col-md-8">
                                <ul class="list-group">
                                    <li class="list-group-item"><strong>Username:</strong>{% if user_object.username %} {{ user_object.username }} {% else %} <p class="text-warning">Not declared</p> {% endif %}</li>
                                    <li class="list-group-item"><strong>First Name:</strong> {% if user_object.first_name %} {{ user_object.first_name }} {% else %} <p class="text-warning">Not declared</p>  {% endif %}</li>
                                    <li class="list-group-item"><strong>Last Name:</strong>{% if user_object.last_name %} {{ user_object.last_name}} {% else %} <p class="text-warning">Not declared</p>  {% endif %}</li>
                                    <li class="list-group-item"><strong>Birth Date:</strong> {% if user_object.profile.birth_date %} {{ user_object.profile.birth_date }} {% else %}<p class="text-warning">Not declared</p>  {% endif %}</li>
{#                                    <li class="list-group-item"><strong>Position:strong</strong>{% strongif user_object.profile.position %} {{ user_object.profile.position }} {% else %} <p class="text-warning">Not declared</p> {% endif %}</li>#}
                                    <li class="list-group-item"><strong>Number:</strong> {% if user_object.profile.number %} {{ user_object.profile.number  }} {% else %} <p class="text-warning">Not declared</p>  {% endif %}</li>
                                    <li class="list-group-item"><strong>Followers</strong>{% if not followers %} Not any followers {% else %} {% for follower in followers %}{{ follower.follower }}{% endfor %}{% endif %} </li>
                                    <li class="list-group-item"><strong>Following</strong>{% if not following %} Not following to anyone {% else %} {% for follow in following %}{{ follow.following }}{% endfor %}{% endif %} </li>


                                </ul>

                                <div class="text-end">
                                    {% if request.user == current_user  %}
                                    <a href="{% url 'edit' %}" class="btn btn-outline-success mt-3">Edit profile</a>
                                    {% endif %}
                                {% if request.user != current_user %}
                                    {% if not is_following %}
                                        <a href="{% url 'follow' user_object.username %}" class="btn btn-outline-secondary mt-3">Follow</a>
                                        {% else %}
                                        <a href="{% url 'unfollow' user_object.username %}" class="btn btn-outline-secondary mt-3">Unfollow</a>
                                    {% endif %}
                                {% endif %}
                                    <a href="{% url 'post-list' %}" class="btn btn-outline-secondary mt-3">Go Back</a>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

assignment1/templates/main-page/user/register.html
{% extends 'main-page/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <h1 class="text-center">Registration</h1>
        <div class="col-md-6">
            <div class="card shadow-lg">
                <div class="card-body">
                    <form action="{% url 'register' %}?next={{ request.GET.next }}" method="post">
                        {% csrf_token %}
                        {% for error in form.non_field_errors %}
                            <p class="alert alert-danger">{{ error }}</p>
                        {% endfor %}

                        {% for error in form.errors %}
                                <p class="text-danger">{{ error }}</p>
                        {% endfor %}

                        <div class="form-group mb-3">
                            <label for="id_username">Username:</label>
                            <input type="text" name="username" id="username" class="form-control">
{#                            {{ form.username }}#}
                        </div>

                        <div class="form-group mb-3">
                            <label for="id_password">Password:</label>
                            <input type="password" name="password" id="password" class="form-control">
{#                            {{ form.password }}#}
                        </div>

                        <div class="form-group mb-3">
                            <label for="id_password_confirm">Password Confirm:</label>
                            <input type="password" name="password_confirm" id="password_confirm" class="form-control">
{#                            {{ form.password_confirm }}#}
                        </div>

                        <div class="form-group mb-3">
                            <label for="id_first_name">First Name:</label>
                            <input type="text" name="first_name" id="first_name" class="form-control">
{#                            {{ form.first_name }}#}
                        </div>

                        <div class="form-group mb-3">
                            <label for="id_last_name">Last Name:</label>
                            <input type="text" name="last_name" id="last_name" class="form-control">
{#                            {{ form.last_name }}#}
                        </div>

                        <div class="form-group mb-3">
                            <label for="id_email">Email:</label>
                            <input type="text" name="email" id="email" class="form-control">
{#                            {{ form.email }}#}
                        </div>

                        <button type="submit" class="btn btn-outline-success btn-block mt-4">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}